### ISSUE TITLE
Replace property javax.persistence.lock.timeout with jakarta.persistence.lock.timeout

### ISSUE THREAD

**Issue by chengfang** [jberet/jberet-jpa-repository#6]
https://github.com/jberet/jberet-jpa-repository/blob/master/src/main/java/org/jberet/jpa/repository/JpaRepository.java

the above class still references the legacy property name `javax.persistence.lock.timeout`, and should be replaced with the current one (jakarta).

**Comment by chengfang** [comment]
@amoscatelli  can you take a look?

**Comment by amoscatelli** [comment]
https://github.com/jberet/jberet-jpa-repository/pull/7

Done !
